name: et3am
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.1
  flutter_native_splash: ^2.4.0
  firebase_auth: ^4.17.9
  flutter_bloc: ^8.1.5
  cloud_firestore: ^4.15.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets\images\splash\Et3am.png




flutter_native_splash:

  color: "#ffffff"
  image: assets/images/splash/Et3am.png
  
  android_12:
    color: "#ffffff"
    image: assets/images/splash/Et3am.png